/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as PresentRouteImport } from './routes/present'
import { Route as ChapterSlugRouteImport } from './routes/chapter.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentRoute = PresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterSlugRoute = ChapterSlugRouteImport.update({
  id: '/chapter/$slug',
  path: '/chapter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playbook': typeof PlaybookRoute
  '/present': typeof PresentRoute
  '/chapter/$slug': typeof ChapterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playbook': typeof PlaybookRoute
  '/present': typeof PresentRoute
  '/chapter/$slug': typeof ChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playbook': typeof PlaybookRoute
  '/present': typeof PresentRoute
  '/chapter/$slug': typeof ChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/playbook' | '/present' | '/chapter/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playbook' | '/present' | '/chapter/$slug'
  id: '__root__' | '/' | '/playbook' | '/present' | '/chapter/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaybookRoute: typeof PlaybookRoute
  PresentRoute: typeof PresentRoute
  ChapterSlugRoute: typeof ChapterSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present': {
      id: '/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$slug': {
      id: '/chapter/$slug'
      path: '/chapter/$slug'
      fullPath: '/chapter/$slug'
      preLoaderRoute: typeof ChapterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaybookRoute: PlaybookRoute,
  PresentRoute: PresentRoute,
  ChapterSlugRoute: ChapterSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
